export const MESSAGE_TYPES = {
  START_CAPTURE: 'START_CAPTURE',
  SELECTION_COMPLETE: 'SELECTION_COMPLETE',
  SELECTION_CANCELLED: 'SELECTION_CANCELLED',
  HIGHLIGHT_ELEMENT: 'HIGHLIGHT_ELEMENT',
  CLEAR_HIGHLIGHT: 'CLEAR_HIGHLIGHT',
} as const

export const PROJECT_ID_PREFIX = 'react-cursor-bridge'

export const PROJECT_NAME_PREFIX = '[React Cursor Bridge]:'

export const STORAGE_KEYS = {
  CAPTURED_IMAGE: 'CAPTURED_IMAGE',
  CAPTURED_ELEMENTS: 'CAPTURED_ELEMENTS',
} as const
